RMET-2623 ::: Fix nil optionsAllowed for Blood Glucose
OutSystems/cordova-outsystems-healthfitness pull request #70
Opened 2022-05-26 17:47 UTC by OS-ricardomoreirasilva

## Description
- The `HealthKitVariable` object associated with "Blood Glucose" is missing a `optionsAllowed` value. This was throwing a unhandled exception that caused an app crash when trying to use Blood Glucose with a disallowed operation.

## Context
https://outsystemsrd.atlassian.net/browse/RPM-2623

## Type of changes
- [X] Fix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [X] Refactor (cosmetic changes)
- [ ] Breaking change (change that would cause existing functionality to not work as expected)

## Platforms affected
- [ ] Android
- [X] iOS
- [ ] JavaScript

## Checklist
- [X] Pull request title follows the format `RMET-XXXX <title>`
- [X] Code follows code style of this project
- [X] CHANGELOG.md file is correctly updated
- [ ] Changes require an update to the documentation
	- [ ] Documentation has been updated accordingly

2022-05-26 19:01 UTC, CarlsCorrea reviewed
I forgot to mention, the xcframework needs to be built using Xcode 12 to work with MABS 7. Otherwise we have an error regarding the version of the compiler. I think @nflsilva can help us on that.

2022-05-27 08:13 UTC, OS-ricardomoreirasilva commented
> I forgot to mention, the xcframework needs to be built using Xcode 12 to work with MABS 7. Otherwise we have an error regarding the version of the compiler. I think @nflsilva can help us on that.

I know what to do ;) Should I use a specific xCode 12 version or is the latest ok?

2022-05-27 08:36 UTC, alexgerardojacinto requested changes

2022-05-27 08:36 UTC, alexgerardojacinto commented on plugin.xml
> +<plugin id="com.outsystems.plugins.healthfitness" version="1.2.4" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
Shouldn't it be version 1.2.3?

2022-05-27 08:36 UTC, CarlsCorrea commented
> > I forgot to mention, the xcframework needs to be built using Xcode 12 to work with MABS 7. Otherwise we have an error regarding the version of the compiler. I think @nflsilva can help us on that.
> 
> I know what to do ;) Should I use a specific xCode 12 version or is the latest ok?

ok, yes can be the latest.

2022-05-27 09:02 UTC, alexgerardojacinto commented on plugin.xml
> +<plugin id="com.outsystems.plugins.healthfitness" version="1.2.4" xmlns="http://apache.org/cordova/ns/plugins/1.0" xmlns:android="http://schemas.android.com/apk/res/android">
Ohhh nevermind, makes sense.

2022-05-27 09:02 UTC, alexgerardojacinto approved these changes

2022-05-27 09:22 UTC, OS-ricardomoreirasilva commented
> > > I forgot to mention, the xcframework needs to be built using Xcode 12 to work with MABS 7. Otherwise we have an error regarding the version of the compiler. I think @nflsilva can help us on that.
> > 
> > 
> > I know what to do ;) Should I use a specific xCode 12 version or is the latest ok?
> 
> ok, yes can be the latest.

Fixed it. It's now building with both MABS 7.2 and 8.1.

![image](https://user-images.githubusercontent.com/97543217/170671207-97f18f56-d6a9-4607-9c98-a02c661be1dc.png)

2022-05-27 09:38 UTC, CarlsCorrea approved these changes

2022-05-27 16:30 UTC, merged